5 задание
igor-tukalo/altexsoft-lab-2020-master pull request #11
Opened 2020-11-01 16:50 UTC by igor-tukalo

5 задание

2020-11-01 17:10 UTC, serhii-shkodenko requested changes
Пожалуйста, поправьте весь код тестов в соответствии с оставленными комментариями.

2020-11-01 17:10 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            unitOfWorkMock = new Mock<IUnitOfWork>();
Мок для `IUnitOfWork` Вы создаете в каждом тесте. Это можно вынести в конструктор. В xUnit конструктор вызывается для каждого теста.

2020-11-01 17:10 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            unitOfWorkMock.Setup(o => o.Repository)
В Moq есть метод для настройки свойств `SetupGet()`. Логичнее использовать именно его в данном случае. Настройку тоже можно вынести в конструктор, если делаете больше одного раза.

2020-11-01 17:10 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            controller = new AmountRecipeIngredientsController(unitOfWorkMock.Object);
Это тоже можно вынести в конструктор.

2020-11-01 17:10 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            await controller.AddAsync(It.IsAny<double>(), It.IsAny<string>(), It.IsAny<int>(), It.IsAny<int>());
Методы `It.IsAny() `и `It.Is() `предназначаются для использования при настройке моков и их верификации. В тестируемые методы обычно передают реальные объекты. Они могут быть как автоматически сгенерированные (например, на основе типов данных) или созданные вручную.

2020-11-01 17:10 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            Assert.True(isAdded);
Здесь также имеет смысл добавить проверку вызова `AddAsync()` с помощью `Verify()`.

2020-11-01 17:10 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            repositoryMock.Setup(o => o.DeleteAsync(It.IsAny<AmountIngredient>())).Callback(() => isDelete = true);
При использовании для проверки `Verify()` небходимость в `Callback()` отпадает, как и в создании булевого флага.

2020-11-01 18:29 UTC, igor-tukalo commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            repositoryMock.Setup(o => o.DeleteAsync(It.IsAny<AmountIngredient>())).Callback(() => isDelete = true);
если я использую Verify() без параметров это значит что будут использоваться ожидания установленные с помощью mock.Setup? или надо тогда заменить _repositoryMock.Setup на 
_repositoryMock.Verify(o => o.AddAsync(It.IsAny<AmountIngredient>()));
просто при использовании
_repositoryMock.Setup(o => o.AddAsync(It.IsAny<AmountIngredient>())) и Verify() без параметров у меня не проверяется выполнение метода AddAsync

2020-11-01 18:44 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            repositoryMock.Setup(o => o.DeleteAsync(It.IsAny<AmountIngredient>())).Callback(() => isDelete = true);
![test_verify](https://user-images.githubusercontent.com/69808191/97811316-805f7d80-1c82-11eb-9b5c-c53c2a9990e3.png)
Я не всё поправил в соответствии со своими комментариями, однако аспект работы `Verify()` продемонстрирован. `Verify()` проверяет все заданные `Setup()`.

2020-11-02 13:21 UTC, serhii-shkodenko requested changes
Поправьте, пожалуйста, оставшиеся контроллеры в соответствии с этими комментариями.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            Assert.Equal(2, amountIngredientsCount);
В целом следует избегать "магических" чисел, встречая которые задумываешься о том, как и почему они появились. Здесь "2" можно заменить на выражение `amountIngredients.Where(x => x.RecipeId == 2).Count()`. Тогда в случае апдейта `amountIngredients`, не придется изменять Assert блок.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            string ingredientName = (await _amountRecipeIngredientsController.GetAmountIngredientNameAsync(1));
Скобки лишние.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            Assert.Equal("Banana", ingredientName);
`"Banana"` лучше заменить на `ingredient.Name`, раз Вы создали переменную `ingredient`.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            Assert.Equal("Bakery products", categoryName);
Использование "магических" строк неясного происхождения. Замените, пожалуйста, на `_category.Name`. Добавьте `_repositoryMock.Verify()`.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +        public async Task GetCategoryById_Should_CategoryName()
Тестируемый метод называется `GetCategoryByIdAsync()`, а здесь только `GetCategoryById()`. Поправьте, пожалуйста. После `Should` нужно добавить глагол. Я думаю `Return` подойдет. Метод `GetCategoryByIdAsync()`, метод возвращает категорию, поэтому именно это и нужно тестировать, а в Assert вы проверили только ее имя. Проверть все свойства модели, `ParentId ` и так далее.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            Assert.Equal(4, categoriesCount);
Снова неясного происхождения константа. Замените, пожалуйста, на `_categories.Where(x => x.ParentId == 2).Count().`

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +        public async Task GetItemsWhereParentId_Should_Count()
Забыли 'Async()' в названии метода, после 'Should' добавьте, пожалуйста, глагол.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +        public async Task RenameCategory_Should_NewName()
Тестируемый метод называется `EditCategoryAsync()`, это никак не отображено в имени теста. Поправьте, пожалуйста.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            await _categoriesController.EditCategoryAsync(1, "Fish", 1);
Использование неясного происхождения констант.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            string updatedName = (await _categoriesController.GetCategoryByIdAsync(1)).Name;
Эту строку лучше убрать в блок Assert и там удостовериться, что поменялось не только имя, но и родительская категория.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            Assert.Equal("Fish", updatedName);
Использование неясного происхождения констант.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +        }
Вот как можно поправить этот тест в соответствии с комментариями:

![rewrited_test](https://user-images.githubusercontent.com/69808191/97871827-aede6680-1d1d-11eb-93f6-dfc3ac25b6d0.png)

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +        public async Task Delete_Should_True()
Добавьте, пожалуйста, глагол в имя этого метода.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            _repositoryMock.Verify();
`// Assert` забыли.

2020-11-02 13:21 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            List<Category> categories = new List<Category>
`// Arrange` забыли.

2020-11-02 14:30 UTC, igor-tukalo commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            repositoryMock.Setup(o => o.DeleteAsync(It.IsAny<AmountIngredient>())).Callback(() => isDelete = true);
Спасибо за проверку! Побродив по просторам интернета я так понял что Verify() проверяет только методы которые в сетапе отмечены методом Verifiable() 
_repositoryMock.Setup(o => o.AddAsync(_amountIngredient)).Verifiable();
иначе я могу просто закомитить 
await _amountRecipeIngredientsController.AddAsync(_amountIngredient.Amount,
                _amountIngredient.Unit, _amountIngredient.RecipeId, _amountIngredient.IngredientId);
и тест пройдет без ошибок.

2020-11-02 17:34 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            repositoryMock.Setup(o => o.DeleteAsync(It.IsAny<AmountIngredient>())).Callback(() => isDelete = true);
Да, вы правы. Чтобы не повторять еще раз в `Verify()` ожидание, необходимио в `Setup()` указывать `Verifiable()`, или или на моке вызвать `VerifyAll()` без указания `Verifiable()`.

2020-11-05 08:38 UTC, serhii-shkodenko commented
Игорь, отметьте, пожалуйста, кнопкой "Resolve conversastion" те предложения, которые Вы внедрили.

2020-11-05 13:44 UTC, serhii-shkodenko requested changes

2020-11-05 13:44 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +        public async Task AddAsync_Should_ReturnVerified()
Лучшим именем, как мне кажется, будет `AddAsync_Should_BeCalled()` или `AddAsync_Should_BeVerified()`, потому что Ваш метод ничего не возвращает. Кроме того, Вы тестируете метод контроллера, а название метода относится к методу репозитория. Поэтому я бы назвал метод как то так: `AddAsync_Runs_Properly()`.

2020-11-05 13:44 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            _repositoryMock.Setup(o => o.AddAsync(It.IsAny<AmountIngredient>())).Verifiable();
Да, Вы здесь не можете настроить ожидание для конкретного объекта, потому что объект создается внтури метода контроллера, однако есть возможность проверить свойства этого объекта:
`It.Is<AmountIngredient>(   entity => entity.Amount == _amountIngredient.Amount &&                entity.IngredientId == _amountIngredient.IngredientId &&                entity.RecipeId == _amountIngredient.RecipeId &&                entity.Unit == _amountIngredient.Unit)`

2020-11-05 13:44 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +        public async Task DeleteAsync_Should_ReturnVerified()
Переименуйте метод, тестируемый метод ничего не возвращает.

2020-11-05 14:20 UTC, igor-tukalo commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +            _repositoryMock.Setup(o => o.AddAsync(It.IsAny<AmountIngredient>())).Verifiable();
О, спасибо! Меня этот вопрос очень интересовал.

2020-11-06 11:58 UTC, serhii-shkodenko requested changes

2020-11-06 11:58 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            Assert.Equal(_category, categoryActual);
Вы здесь хотите проверить, что из настроенного Вами мока вернется такой ожидаемый объект, который будет равен фактическому значению. Однако `Assert.Equal()` для этого не годится, потому что вызывает `object.Equals()`, который для ссылочных типов проверяет по ссылке, то есть фактически проверяя, что это один и тот же объект. Для изменения этого поведения можно, например, перегрузить `object.Equals()` и `GetHashCode()`, однако это не наш случай. Чтобы явно указать, что Вы ожидаете возврата того же объекта, который Вы указали вернуть моку, необходимо использовать `Assert.Same()`. Поправьте пожалуйста, во всех тестах для аналогичных случаев.

2020-11-06 11:58 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            Assert.Equal(updatedCategory.Name, updatedCategory.Name);
Очевидно, что в одном случае имелось в виду `updateCategory` вместо `updatedCategory`. Следующую строку тоже поправьте.

2020-11-06 11:58 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            Category updateCategory = new Category() { Id = _category.Id, Name = "Fish", ParentId = (int)_category.ParentId };
Эту переменную лучше назватть `сategoryToUpdate`.

2020-11-06 11:58 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +        }
В целом этот тест некорретный. Вот код метода: 
```
public async Task EditCategoryAsync(int categoryId, string newName, int newParentId)
{
    Category category = await GetCategoryByIdAsync(categoryId);
    category.Name = newName;
    category.ParentId = newParentId;
    await UnitOfWork.Repository.UpdateAsync(category);
}
```
В тесте следует:
1. В тестируемый метод передать новые значения для категории. Done.
2. Настроить ожидание для `GetCategoryByIdAsync()`. Done.
3. Проверить, что в `UpdateAsync()` в качестве аргумента была передана категория с уже измененными полями. Not done. Для этого воспользуйтесь `It.Is<>()`.

2020-11-10 13:32 UTC, serhii-shkodenko requested changes

2020-11-10 13:32 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +        }
Вот код Вашего тестируемого метода:
```
public async Task<string> GetAmountIngredientNameAsync(int ingredientId)
{
      return (await UnitOfWork.Repository.GetByIdAsync<Ingredient>(ingredientId)).Name;
}
```
Для того чтобы протестировать этот код, создавать объект `Ingredient` явно излишне. Здесь будет достаточно передать в метод `GetAmountIngredientNameAsync()` любую переменную с типом `int`, проверить, что она попала в `GetByIdAsync()`. Также нужно настроить ожидание для `GetByIdAsync()`, проверить его и проверить, что результат выполнения тестируемого метода соответствует тому, что вернет настроенный метод `GetByIdAsync()`. Да, Вы делаете нужные шаги, однако создание объекта `Ingredient` усложняет тест.

2020-11-10 13:32 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            Category сategoryToUpdate = new Category() { Id = _category.Id, Name = "Fish", ParentId = (int)_category.ParentId };
Здесь не нужно явное приведение типов. И слева, и справа у Вас `Nullable<int>`.

2020-11-10 13:32 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +        }
Еще раз обращаю Ваше внимание, что согласно сигнатуре Вашего метода `Task EditCategoryAsync(int categoryId, string newName, int newParentId)`, возвращенной категории, следует присвоить **новые** имена, которые Вы передаете. Однако Вы этого не делаете, почему-то передавая в тестируемый метод уже существующие `Name` и `ParentId`. Это приводит к тому, что Ваш тест проходит, если закомментировать код, отвечающий за изменение этих значений:
![test_is_passing](https://user-images.githubusercontent.com/69808191/98680271-d6f74680-2369-11eb-9513-c642fde9d4e2.jpg)

2020-11-10 13:59 UTC, serhii-shkodenko requested changes

2020-11-10 13:59 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            Assert.Equal(expectedValue, categoriesCount);
Сравнение коллекций в юнит тестировании не самая тривиальная задача, и сравнение количества элементов в коллекциях может быть полезным. Однако в Вашем случае достаточно будет проверить, что из тестируемого метода вернулось то же ожидаемое значение, которое Вы настроили для `GetListWhereAsync()`: `Assert.Same(expectedResult, result);`, где обе переменные это `List<Category>`.

2020-11-10 13:59 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CookingStepsControllerTests.cs
> +            List<CookingStep> cookingStepWhereRecipeId = _cookingSteps.Where(x => x.RecipeId == _cookingStep.RecipeId).ToList();
Эту переменную я бы назвал `expectedResult`.

2020-11-10 13:59 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CookingStepsControllerTests.cs
> +            Assert.Equal(cookingStepWhereRecipeId.Count(), cookingStepsCount);
Аналогично здесь, сравнение коллекций значительно более надежно, чем проверка количества элементов в них. Используйте `Assert.Same()`.

2020-11-10 13:59 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            List<Category> categoriesSearch = _categories.Where(x => x.Name.ToLower().Contains(sarchValue)).ToList();
Эту переменную я бы назвал `expectedResult`.

2020-11-10 13:59 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            int categoriesCount = (await _categoriesController.FindCategoriesAsync(sarchValue)).Count;
Эту переменную я бы назвал `result`.

2020-11-10 13:59 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CookingStepsControllerTests.cs
> +            int cookingStepsCount = (await _cookingStepsController.GetCookingStepsWhereRecipeIdAsync(_cookingStep.RecipeId)).Count;
Эту переменную я бы назвал `result`.

2020-11-10 13:59 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            Assert.Equal(_categories.Count, categoriesCount);
Сравнивайте не количенства элементов в коллекциях, а сами коллекции. Здесь Вам прекрасно подойдет `Assert.Same()`.

2020-11-10 13:59 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CookingStepsControllerTests.cs
> +        public async Task GetCookingStepById_Should_ReturnCookingStepById()
Из фразы `ReturnCookingStepById` часть `ById` можно удалить.

2020-11-10 18:10 UTC, serhii-shkodenko requested changes

2020-11-10 18:10 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CookingStepsControllerTests.cs
> +        }
Этот тест слишком переусложнен. Достаточно сделать следующее:
![edit_cooking_step2](https://user-images.githubusercontent.com/69808191/98711931-54cd4900-238e-11eb-97b0-c99f2c09c348.jpg)

2020-11-10 18:10 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CookingStepsControllerTests.cs
> +        }
В тесте не протестирована бизнес логика, которая предуматривает изменение порядковых номеров в шагах приготовления, следующих после удаляемого шага приготовления. Если в тестируемом методе ее закомментировать, тест все равно проходит. 
![delete_cooking_step](https://user-images.githubusercontent.com/69808191/98713746-a8d92d00-2390-11eb-8e0e-5b0edaa5e004.jpg)

2020-11-10 18:48 UTC, serhii-shkodenko requested changes

2020-11-10 18:48 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/IngredientsControllerTests.cs
> +            Assert.Equal(_customSettings.NumberConsoleLines, numberBatches);
Здесь у Вас есть возможность сравнить коллекции, а не количество элементов в них.

2020-11-10 18:48 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/IngredientsControllerTests.cs
> +            Assert.Equal(_ingredients.Count, categoriesCount);
Здесь у Вас есть возможность сравнить коллекции, а не количество элементов в них.

2020-11-10 18:48 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/IngredientsControllerTests.cs
> +        }
Переусложненный тест, просто возвращаете из `GetListWhereAsync()` список и проверяете, что он вернулся из тестируемого метода.

2020-11-10 18:48 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/IngredientsControllerTests.cs
> +            Assert.Same(_ingredient, ingredientToDelete);
Лишняя проверка, ее можно удалить.

2020-11-10 19:37 UTC, serhii-shkodenko requested changes

2020-11-10 19:37 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/RecipesControllerTests.cs
> +            Assert.Equal(recipesCategoryId.Count, recipesCount);
Сравнивайте коллекции, а не количество элементов в них.

2020-11-10 19:37 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/RecipesControllerTests.cs
> +            // Arrange
Этот комментарий должен быть раньше объявления переменной.

2020-11-10 19:37 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/RecipesControllerTests.cs
> +            // Arrange
Этот комментарий должен быть раньше объявления переменной.

2020-11-11 08:14 UTC, igor-tukalo commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +        }
Не совсем понял, ведь GetByIdAsync() должен вернуть обьект Ingredient. Нельзя добавить обьект Ingredient к свойству поля _amountIngredient.Ingredient обьявляемого в конструкторе?

2020-11-11 15:12 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/AmountRecipeIngredientsControllerTests.cs
> +        }
Да, конечно, Вы правы. Замечание снимается.

2020-11-12 11:27 UTC, serhii-shkodenko approved these changes
Поправьте эти мелкие недочеты и после вердикта @alex-geraschenko можно будет мержить.

2020-11-12 11:27 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/BaseTests.cs
> +        protected Mock<IUnitOfWork> _unitOfWorkMock;
Забыли здесь `readonly` добавить.

2020-11-12 11:27 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/CategoriesControllerTests.cs
> +            string sarchValue = "a";
Здесь опечатка. Должно быть s**e**archValue.

2020-11-12 11:27 UTC, serhii-shkodenko commented on HomeTask5.Core.Tests/IngredientsControllerTests.cs
> +            string sarchValue = "a";
Здесь опечатка. Должно быть s**e**archValue.

2020-11-17 19:12 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-11-17 20:26 UTC, merged