Tasks/task1
igor-tukalo/altexsoft-lab-2020-master pull request #3
Opened 2020-08-03 22:02 UTC by IgorTukalo

Убрал код из master.

2020-08-04 10:35 UTC, alex-geraschenko requested changes
Разнесите методы задач по разным классам, чтобы это соответствовало принципам SOLID

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +            while (validChangepath == false)
Это выражение можно упростить до `while (!validChangepath)`

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                if (answer == "y" || answer == "Y")
Это выражение можно упростить до `if (answer.ToLower() == "y")`

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                else if (answer == "n" || answer == "N")
Это выражение можно упростить до `if (answer.ToLower() == "n")`

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +            string path = @"D:\Work\Altexsoft\task1\origin.txt";
Что будет, если такого пути не существует ?

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                    using (StreamReader sr = new StreamReader(path, System.Text.Encoding.Default))
Обратите внимание на статические методы из `File`

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +            string newPath = @"D:\Work\Altexsoft\task1\test.txt";
Что будет, если такого пути не существует ?

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +            string path = @"D:\Work\Altexsoft\task1\origin.txt";
Что будет, если такого пути не существует ?

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                    using (StreamReader sr = new StreamReader(path, System.Text.Encoding.Default))
Обратите внимание на статические методы из `File`

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                commaWords += fileTextMass[i] + ", ";
Обратите внимание на `string.Join`

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +            string path = @"D:\Work\Altexsoft\task1\origin.txt";
Что будет, если такого пути не существует ?

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                    using (StreamReader sr = new StreamReader(path, System.Text.Encoding.Default))
Обратите внимание на статические методы из `File`

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                while (validStart == false)
Это выражение можно упростить

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/Program.cs
> +            while (validStart == false)
Это выражение можно упростить

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/Program.cs
> +                        while (validMenuSelectMethods == false)
Это выражение можно упростить

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/Program.cs
> +                            if (answer == "y" || answer == "Y")
Это выражение можно упростить

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/Program.cs
> +                            else if (answer == "n" || answer == "N")
Это выражение можно упростить

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +            while (validStart == false)
Это выражение можно упростить

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +using System.Security.Cryptography.X509Certificates;
Зачем здесь криптография?

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +            for (int i = 0; i < fileTextMass.Length; i++)
Здесь можно обойтись без цикла

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                Console.WriteLine("id: " + maxId + "| " + "Change root directory");
Обратите внимание на `string.Format` или **string interpolation**

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +            fileTextMass = fileText.ToString().Split(new[] { ' ', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);
Совместите объявление переменной и присваивание в одну строку

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +            fileInfos = new List<FileInform>();
Поле `fileInfos` лучше сделать локальной переменной и возвращать из этого метода

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                foreach (string s in dirs)
Не хватает сортировки

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                foreach (string s in files)
Не хватает сортировки

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                    id++;
Если нужен `id`, то лучше использовать `for` вместо `foreach`

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                    Console.WriteLine("id: " + flinf.Id + "| " + flinf.Name);
Обратите внимание на `string.Format` или **string interpolation**

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                    Console.WriteLine("id: " + flinf.Id + "| " + flinf.Name);
Обратите внимание на `string.Format` или **string interpolation**

2020-08-04 10:35 UTC, alex-geraschenko commented on task1/FileManegment.cs
> +                Console.WriteLine("id: " + dirInf.Id + "| " + dirInf.PrevPath);
Обратите внимание на `string.Format` или **string interpolation**

2020-08-04 19:28 UTC, IgorTukalo commented
Жду новых замечаний.

2020-08-07 10:36 UTC, alex-geraschenko requested changes

2020-08-07 10:36 UTC, alex-geraschenko commented on task1/Method3Control.cs
> +                if (File.Exists(path))
Проверка на существование файла дублируется. Попробуйте использовать базовый класс и наследование

2020-08-07 10:36 UTC, alex-geraschenko commented on task1/Method2Control.cs
> +                if (File.Exists(path))
Проверка на существование файла дублируется. Попробуйте использовать базовый класс и наследование

2020-08-07 10:36 UTC, alex-geraschenko commented on task1/Method2Control.cs
> +                StringBuilder fileText = new StringBuilder();
Использование `StringBuilder` в данном случае не рационально

2020-08-07 10:36 UTC, alex-geraschenko commented on task1/Method1Control.cs
> +                if (File.Exists(path))
Проверка на существование файла дублируется. Попробуйте использовать базовый класс и наследование

2020-08-07 10:36 UTC, alex-geraschenko commented on task1/MenuControl.cs
> +            while (!validStart)
Цикл `while` можно заменить на `do..while` и тогда уйти от дублирования вызова `Validation.ValidNumber`

2020-08-12 13:56 UTC, alex-geraschenko approved these changes
Выглядит хорошо. Можно мержить

2020-08-12 17:05 UTC, merged