Tasks/task2
igor-tukalo/altexsoft-lab-2020-master pull request #4
Opened 2020-08-18 22:50 UTC by IgorTukalo

2020-08-21 16:55 UTC, alex-geraschenko requested changes
Постарайтесь реализовать шаблоны `Repository/UnitOfWork`

2020-08-26 13:22 UTC, alex-geraschenko requested changes
Очень много напешаного и напутаного кода. Я бы сказал, что нарушается принцип KIS.
Я не стал дублировать комментарии для всех классов. Постарайтесь пройти по всему приложению и упростить/переписать по примеру существующих комментариев. И разнесите логику работы с сущностями и логику взаимодействия с консолью. Сущности не должны быть элементами меню

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +            unitOfWork = new UnitOfWork();
Нарушение принципа **Dependency Inversion**

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                ItemsMenu = new List<EntityMenu>
Поправьте форматирование

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                BuildHierarchicalMenu(new List<EntityMenu>(unitOfWork.Categories.GetAll().ToList()), parent, 1);
Дублирование кода `unitOfWork.Categories.GetAll().ToList()`

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                new CategoriesControl().GetMenuItems();
Зачем создавать **CategoriesControl** внутри **CategoriesControl** ?

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +    public class CategoriesControl : MenuNavigation
Класс нарушает принцип **Single Responsibility** т.к. делает 2 задачи: управляет категориями и отображает меню

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +            Console.Clear();
Нарушение принципа **Dependency Inversion**

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/IngredientsControl.cs
> +            unitOfWork = new UnitOfWork();
Нарушение принципа **Dependency Inversion**

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/IngredientsControl.cs
> +            Console.Clear();
Нарушение принципа **Dependency Inversion**

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/IngredientsControl.cs
> +    public class IngredientsControl : MenuNavigation
Класс нарушает принцип Single Responsibility т.к. делает 2 задачи: управляет ингридиентами и отображает меню

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/IngredientsControl.cs
> +                string nameIngredient = Validation.IsNameMustNotExist(new List<EntityMenu>(unitOfWork.Ingredients.GetAll()), Console.ReadLine());
Дублирование кода `unitOfWork.Ingredients.GetAll()`

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +            get
Этот код можно упростить до **Expression Bodied Property**

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +            {
Этот код можно упростить до **Expression Bodied Property**

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +            get
Этот код можно упростить до **Expression Bodied Property**

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +            get
Этот код можно упростить до **Expression Bodied Property**

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +            get
Этот код можно упростить до **Expression Bodied Property**

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Repositories/StepCookingRepository.cs
> +    public class StepCookingRepository : IRepository<StepCooking>
С точки зрения английского языка правильнее `CookingStep`,  а не `StepCooking`

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                BuildHierarchicalMenu(new List<EntityMenu>(unitOfWork.Categories.GetAll().ToList()), parent, 1);
Нет смысла создавать новый список

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                string nameMainCategory = Validation.IsNameMustExist(new List<EntityMenu>(unitOfWork.Categories.GetAll().ToList()), Console.ReadLine());
Нет смысла создавать новый список

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                var parent = unitOfWork.Categories.GetAll().ToList().Find((x) => x.Id == IdMenu);
Вместо `GetAll().ToList().Find((x) => x.Id == IdMenu)` используйте `Get(IdMenu)`

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                string nameMainCategory = Validation.IsNameMustExist(new List<EntityMenu>(unitOfWork.Categories.GetAll().ToList()), Console.ReadLine());
Дублирование кода `unitOfWork.Categories.GetAll()`

2020-08-26 13:22 UTC, alex-geraschenko commented on task2/Controls/IngredientsControl.cs
> +                string nameIngredient = Validation.IsNameMustNotExist(new List<EntityMenu>(unitOfWork.Ingredients.GetAll()), Console.ReadLine());
Нет смысла создавать новый список

2020-08-31 09:43 UTC, alex-geraschenko requested changes
Пересмотрите код. Много где нарушен принцип **DRY**.
Многие классы можно упростить либо применив наследование и базовые классы, либо использую `Generic`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                int idMainCategory = (from t in unitOfWork.Categories.GetAll()
Дублирование кода `unitOfWork.Categories.GetAll()`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +            foreach (var r in unitOfWork.Recipes.GetAll().ToList().Where(x => x.IdCategory == thisEntity.Id))
Вызов `ToList` избыточен

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                foreach (var a in unitOfWork.AmountIngredients.GetAll().ToList().Where(x => x.IdRecipe == r.Id))
Вызов `ToList` избыточен

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                foreach (var a in unitOfWork.CookingSteps.GetAll().ToList().Where(x => x.IdRecipe == r.Id))
Вызов `ToList` избыточен

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/CookingStepsControl.cs
> +            int CurrentStep = unitOfWork.CookingSteps.GetAll().Where(x => x.IdRecipe == recipeId).Count() > 0 ?
Дублирование вызова `unitOfWork.CookingSteps.GetAll()`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/CookingStepsControl.cs
> +                foreach (var s in unitOfWork.CookingSteps.GetAll().Where(x => x.IdRecipe == idRecipe))
Дублирование вызова `unitOfWork.CookingSteps.GetAll()`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/CookingStepsControl.cs
> +                unitOfWork.SaveDataTable("CookingSteps.json", JsonConvert.SerializeObject(unitOfWork.CookingSteps.GetAll()));
Дублирование вызова `unitOfWork.CookingSteps.GetAll()`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/CookingStepsControl.cs
> +                foreach (var s in unitOfWork.CookingSteps.GetAll().Where(x => x.IdRecipe == idRecipe && x.Step > unitOfWork.CookingSteps.Get(idCookingStep).Step))
Лучше вынести этот код из цикла `unitOfWork.CookingSteps.Get(idCookingStep)`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/IngredientsControl.cs
> +                unitOfWork.SaveDataTable("Ingredients.json", JsonConvert.SerializeObject(unitOfWork.Ingredients.GetAll()));
Дублирование вызова `unitOfWork.Ingredients.GetAll()`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/RecipeIngredientsControl.cs
> +            int idAmountIngredients = unitOfWork.AmountIngredients.GetAll().Count() > 0 ? unitOfWork.AmountIngredients.GetAll().Max(x => x.Id) + 1 : 1;
Дублирование вызова `unitOfWork.AmountIngredients.GetAll()`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/RecipeIngredientsControl.cs
> +                foreach (var a in unitOfWork.AmountIngredients.GetAll().Where(x => x.IdRecipe == idRecipe))
Дублирование вызова `unitOfWork.AmountIngredients.GetAll()`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/RecipesControl.cs
> +                foreach (var a in unitOfWork.AmountIngredients.GetAll().Where(x => x.IdRecipe == recipe.Id))
Дублирование вызова `unitOfWork.AmountIngredients.GetAll()`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/RecipesControl.cs
> +            int idRecipe = unitOfWork.Recipes.GetAll().Count() > 0 ? unitOfWork.Recipes.GetAll().Max(x => x.Id) + 1 : 1;
Дублирование вызова `unitOfWork.Recipes.GetAll()`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/RecipesControl.cs
> +                foreach (var a in unitOfWork.AmountIngredients.GetAll().ToList().Where(x => x.IdRecipe == idRecipe))
Избыточный вызов `ToList`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/RecipesControl.cs
> +                foreach (var a in unitOfWork.CookingSteps.GetAll().ToList().Where(x => x.IdRecipe == idRecipe))
Избыточный вызов `ToList`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/RecipesControl.cs
> +            if (level <= levelLimitation)
Если инвертировать условие, то можно уйти от одного уровня вложенности

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/RecipesControl.cs
> +            if (Validation.YesNo() == ConsoleKey.Y)
Если инвертировать условие, то можно уйти от одного уровня вложенности

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/IngredientsControl.cs
> +            if (Validation.YesNo() == ConsoleKey.Y)
Если инвертировать условие, то можно уйти от одного уровня вложенности

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/CookingStepsControl.cs
> +            if (Validation.YesNo() == ConsoleKey.Y)
Если инвертировать условие, то можно уйти от одного уровня вложенности

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +            if (Validation.YesNo() == ConsoleKey.Y)
Если инвертировать условие, то можно уйти от одного уровня вложенности

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Properties/Resources.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
Какое назначение этого файла ?

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Repositories/AmountIngredientRepository.cs
> +            AmountIngredient amountIngredient = (from a in db.AmountIngredients
Чтобы не дублировать код, используйте `Get`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Repositories/CategoryRepository.cs
> +            Category category = (from c in db.Categories
Чтобы не дублировать код, используйте `Get`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Repositories/CookBookContext.cs
> +            File.WriteAllText(GetJsonPathFile("Recipes.json"), JsonConvert.SerializeObject(Recipes));
Переиспользуйте `SaveChanges`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Repositories/CookBookContext.cs
> +        public void SaveChanges(string jsonName,string content)
Этот метод лучше сделать приватным, и вместо него всегда использовать `SaveAllData`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Repositories/CookingStepRepository.cs
> +            CookingStep stepCooking = (from s in db.CookingSteps
Чтобы не дублировать код, используйте `Get`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Repositories/IngredientRepository.cs
> +            Ingredient ingredient = (from i in db.Ingredients
Чтобы не дублировать код, используйте `Get`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Repositories/RecipeRepository.cs
> +            Recipe recipe = (from r in db.Recipes
Чтобы не дублировать код, используйте `Get`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +        private readonly CookBookContext db = new CookBookContext();
По сути, `UnitOfWork` и `CookBookContext` - одно и тоже. Постарайтесь их объединить

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Validation.cs
> +            int NumId=0;
Локальные переменные принято называть в `camelCasel`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Validation.cs
> +            double NumId=0;
Локальные переменные принято называть в `camelCasel`

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/ViewNavigation/ContextMenuNavigation/CookingContextMenuNavigation.cs
> +                        new ProgramMenu(new CookingStepsNavigation(new CookingStepsControl(CookingSteps.IdRecipe))).CallMenu();
Дублирование кода

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/ViewNavigation/ContextMenuNavigation/CookingContextMenuNavigation.cs
> +                        new ProgramMenu(new CookingStepsNavigation(new CookingStepsControl(CookingSteps.IdRecipe))).CallMenu();
Дублирование кода

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/ViewNavigation/ContextMenuNavigation/IngredientsContextMenuNavigation.cs
> +                        new ProgramMenu(ingredientsNavigation).CallMenu();
Дублирование кода

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/ViewNavigation/ContextMenuNavigation/IngredientsContextMenuNavigation.cs
> +                        new ProgramMenu(ingredientsNavigation).CallMenu();
Дублирование кода

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/ViewNavigation/ContextMenuNavigation/CategoriesContextMenuNavigation.cs
> +                        new ProgramMenu(new CategoriesNavigation(new CategoriesControl())).CallMenu();
Дублирование кода

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/ViewNavigation/ContextMenuNavigation/CategoriesContextMenuNavigation.cs
> +                        new ProgramMenu(new CategoriesNavigation(new CategoriesControl())).CallMenu();
Дублирование кода

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/ViewNavigation/Navigation.cs
> +        public void GetNavigation(List<EntityMenu> menuItems, Method selectedMethod)
Если название метода начинаетс с `Get`, то он должен возвращать значение.

2020-08-31 09:43 UTC, alex-geraschenko commented on task2/Interfaces/INavigation.cs
> +        void GetNavigation();
Если название метода начинаетс с `Get`, то он должен возвращать значение.

2020-08-31 12:19 UTC, igor-tukalo commented on task2/Controls/CategoriesControl.cs
> +                int idMainCategory = (from t in unitOfWork.Categories.GetAll()
если я создам класс MainControl от которого будут наследоваться все мои Control классы. и в конструкторе MainControl передавать List<Recipe> Recipes = unitOfWork.Categories.GetAll() и другие списки, а также создать методы общие для переопределения. это не нарушает принцип DIP?

2020-08-31 12:29 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                int idMainCategory = (from t in unitOfWork.Categories.GetAll()
Пока не очень понял, что Вы хотите сделать. Если Вы хотите сделать `MainControl` базовым, то и называться он должен  иначе. И в базовом классе может только общее для всех наследников

2020-08-31 13:18 UTC, igor-tukalo commented on task2/Controls/CategoriesControl.cs
> +                int idMainCategory = (from t in unitOfWork.Categories.GetAll()
Хочу создать для всех классов Controls общий базовый класс и перенести туда одинаковые поля и методы, но у меня в наследниках похожие алгоритмы, содержащие похожие шаги. Например add, edit, delete. Получается одинаковые шаги методов перенесу в базовый класс, а в подклассах оставлю реализацию того что будет отличатся.

2020-08-31 14:56 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +                int idMainCategory = (from t in unitOfWork.Categories.GetAll()
ОК. Так и назовите - `BaseControl`

2020-09-02 08:56 UTC, alex-geraschenko requested changes
Похоже, что Вы не очень разобрались с шаблонами `Repository` и `UnitOFWork`. Посмотрите тут пример реализации этих шаблонов https://www.infoworld.com/article/3107186/how-to-implement-the-repository-design-pattern-in-c.html

2020-09-02 08:56 UTC, alex-geraschenko commented on task2/Controls/BaseControl.cs
> +        public CookBookContext DBControl { get; set; }
Не самое удачное имя для свойства, т.к. тип у Вас содержит слово `Context`

2020-09-02 11:10 UTC, igor-tukalo commented on task2/Controls/BaseControl.cs
> +        public CookBookContext DBControl { get; set; }
В моей реализации есть интерфейс IRepository и классы репозитории, реализующие интерфейс IRepository.  Я просто раньше создавал еще классы для управления репозиториями. CookBookContext где для каждой сущности было прописано получение данных из json. И класс UnitOfWork в нем предоставлял доступ к репозиториям  и определял общий контекст для репозиториев. Сейчас обьеденил все в один класс CookBookContext, что имя неудачно я согласен. Я так понимаю CookBookContext должен называться UnitOfWork. Или часть с UnitOfWork следует иначе реализовать?

2020-09-02 14:37 UTC, alex-geraschenko commented on task2/Controls/BaseControl.cs
> +        public CookBookContext DBControl { get; set; }
По сути да - `UnitOfWork` и есть контекст

2020-09-02 14:53 UTC, alex-geraschenko commented on task2/Controls/BaseControl.cs
> +        public CookBookContext DBControl { get; set; }
Вот пример реализации `UnitOfWork`
```
public class UnitOfWork : IUnitOfWork
{
    // поля
    private readonly DbContext dataBaseContext;

    private readonly IUserRepository userRepository;
    private readonly IApartmentRepository apartmentRepository;
    private readonly IBillRepository billRepository;

    // конструктори
    public UnitOfWork(DbContext dataBaseContext)
    {
        this.dataBaseContext = dataBaseContext;

        this.userRepository = new UserRepository(dataBaseContext);
        this.apartmentRepository = new ApartmentRepository(dataBaseContext);
        this.billRepository = new BillRepository(dataBaseContext);
    }

    // властивості
    public IUserRepository UserRepository => userRepository;
    public IApartmentRepository ApartmentRepository => apartmentRepository;
    public IBillRepository BillRepository => billRepository;

    // методи
    public int Save()
    {
        return dataBaseContext.SaveChanges();
    }
}
```

2020-09-02 17:57 UTC, alex-geraschenko requested changes

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Repositories/IngredientRepository.cs
> +            } while (Items.Exists(x => x.Name.ToLower() == name.ToLower()));
В этом случае лучше применить обычный `while`

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Repositories/RecipeRepository.cs
> +            } while (Items.Exists(x => x.Name.ToLower() == name.ToLower()));
В этом случае лучше применить обычный `while`

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Repositories/CategoryRepository.cs
> +            } while (Items.Exists(x => x.Name.ToLower() == name.ToLower()));
В этом случае лучше применить обычный `while`

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Interfaces/IBaseControl.cs
> +        public UnitOfWork UnitOfWork { get; set; }
В интерфейсе все свойства и методы и так публичные. Дополнительный модификатор не нужен

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +        public CategoryRepository Categories => categoryRepository ?? categoryRepository;
Это выражение лишено смысла

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +            return UnitOfWork.Categories.Get(id);
Лучше сделать приватное поле для `CategoryRepository` и проинициализировать его в конструкторе
```
private readonly categoryRepository;

public CategoriesControl(IUnitOfWork unitOfWork) : base(unitOfWork)
{
    categoryRepository = UnitOfWork.Categories;
}
```

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +            base.Add();
Вместо вызова базового метода лучше напрямую вызывать `UnitOfWork.SaveAllChanges`.

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +            base.Edit(id);
Вместо вызова базового метода лучше напрямую вызывать `UnitOfWork.SaveAllData`.

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +            base.Delete(id);
Вместо вызова базового метода лучше напрямую вызывать `UnitOfWork.SaveAllData`.

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Controls/CookingStepsControl.cs
> +            base.Add();
Вместо вызова базового метода лучше напрямую вызывать `UnitOfWork.SaveAllData`.

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Controls/CookingStepsControl.cs
> +            base.Edit(id);
Вместо вызова базового метода лучше напрямую вызывать `UnitOfWork.SaveAllData`.

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Controls/CookingStepsControl.cs
> +            base.Delete(id);
Вместо вызова базового метода лучше напрямую вызывать `UnitOfWork.SaveAllData`.

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Controls/BaseControl.cs
> +            UnitOfWork.SaveAllData();
Методы `Add', `Edit`, `Delete` больше запутывают код, чем помогают. Лучше их убрать

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +        public string GetJsonData(string jsonFileName)
Логику этого метода стоит вынести в отдельный `JsonManager`

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +        public string GetJsonPathFile(string jsonFileName)
Логику этого метода стоит вынести в отдельный `JsonManager`

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +            categoryRepository = new CategoryRepository(JsonConvert.DeserializeObject<List<Category>>(GetJsonData("Categories.json")));
Десериализацию лучше вынести в `JsonManager`

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +            SaveChanges("Recipes.json", JsonConvert.SerializeObject(Recipes.Items));
Cериализацию лучше вынести в `JsonManager`

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +            File.WriteAllText(GetJsonPathFile(jsonName), content);
Логику этого метода стоит вынести в отдельный `JsonManager`

2020-09-02 17:57 UTC, alex-geraschenko commented on task2/Repositories/UnitOfWork.cs
> +            categoryRepository = new CategoryRepository(JsonConvert.DeserializeObject<List<Category>>(GetJsonData("Categories.json")));
Имена файлов можно генерировать при помощи `typeof(T).Name + ".json"`

2020-09-02 17:59 UTC, alex-geraschenko commented on task2/Repositories/AmountIngredientRepository.cs
> +        public AmountIngredientRepository(List<AmountIngredient> context)
Большую часть логики можно вынести в базовый класс `BaseRepository<T>`

2020-09-03 08:34 UTC, igor-tukalo commented on task2/Controls/CategoriesControl.cs
> +            return UnitOfWork.Categories.Get(id);
а если я в базовом классе создам такой конструктор.

    public abstract class BaseControl : IBaseControl
    {
        public IUnitOfWork UnitOfWork { get; set; }

        public BaseControl(IUnitOfWork unitOfWork)
        {
            UnitOfWork = unitOfWork;
        }
    }
тогда конструктор производного будет

        public CategoriesControl(IUnitOfWork unitOfWork) : base(unitOfWork)
        {
        }
я смогу обращаться к своим репозиториям просто через UnitOfWork он же все ровно будет публичным
чтобы не писать для каждого репозитория свое поле
private readonly categoryRepository;
private readonly recipesRepository;
так можно сделать?

2020-09-03 14:40 UTC, alex-geraschenko requested changes

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Controls/BaseControl.cs
> +        public IUnitOfWork UnitOfWork { get; set; }
Свойство и конструктор лучше сделать `protected`

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Controls/CategoriesControl.cs
> +            return UnitOfWork.Categories.Get(id);
Можно, но тогда у Вас может быть дублирование кода. Например:
```
UnitOfWork.Categories.Add(...)
UnitOfWork.Categories.Get()
UnitOfWork.Categories.Update()
....
```
или 
```
categoryRepository = UnitOfWork.Categories;

categoryRepository.Add(...)
categoryRepository.Get()
categoryRepository.Update()
```
как лучше?

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Controls/CookingStepsControl.cs
> +            IdRecipe = idRecipe;
По-моему в этом свойстве нет необходимости

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Controls/RecipeIngredientsControl.cs
> +            IdRecipe = idRecipe;
По-моему в этом свойстве нет необходимости

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Interfaces/IBaseControl.cs
> +        public IUnitOfWork UnitOfWork { get; set; }
В интерфейсах все свойства и методы по умолчанию `public`, поэтому дополнительно это указывать не надо

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/AmountIngredientRepository.cs
> +            var amountIngredient = Get(id);
Этот код можно вынести в базовый класс

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/AmountIngredientRepository.cs
> +            return (from a in Items
Этот код можно вынести в базовый класс

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/CategoryRepository.cs
> +            var category = Get(id);
Этот код можно вынести в базовый класс

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/CategoryRepository.cs
> +            return (from c in Items
Этот код можно вынести в базовый класс

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/CookingStepRepository.cs
> +            var stepCooking = Get(id);
Этот код можно вынести в базовый класс

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/CookingStepRepository.cs
> +            return (from s in Items
Этот код можно вынести в базовый класс

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/AmountIngredientRepository.cs
> +    class AmountIngredientRepository : BaseRepository<AmountIngredient>, IRepository<AmountIngredient>
Если `BaseRepository<T>` будет реализоввывать `IRepository<T>`, то не надо будет дополнительно указывать `IRepository<AmountIngredient>`

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/CategoryRepository.cs
> +    class CategoryRepository : BaseRepository<Category>, IRepository<Category>
Если `BaseRepository<T>` будет реализоввывать `IRepository<T>`, то не надо будет дополнительно указывать `IRepository<Category>`

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/CookingStepRepository.cs
> +    class CookingStepRepository : BaseRepository<CookingStep>, IRepository<CookingStep>
Если `BaseRepository<T>` будет реализоввывать `IRepository<T>`, то не надо будет дополнительно указывать `IRepository<CookingStep>`

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/IngredientRepository.cs
> +    class IngredientRepository : BaseRepository<Ingredient>, IRepository<Ingredient>
Если `BaseRepository<T>` будет реализоввывать `IRepository<T>`, то не надо будет дополнительно указывать `IRepository<CookingStep>`

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/IngredientRepository.cs
> +            var ingredient = Get(id);
Этот метод можно вынести в базовый класс

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/IngredientRepository.cs
> +            return (from i in Items
Этот метод можно вынести в базовый класс

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/JsonManager.cs
> +        public void JsonSerializer<T>(List<T> items) where T : class
Имена методов должны быть глаголами. В данном случае лучше назвать `Save`

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/JsonManager.cs
> +        public List<T> JsonDeSerializer<T>() where T : class
Имена методов должны быть глаголами. В данном случае лучше назвать `Read`

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/RecipeRepository.cs
> +    class RecipeRepository : BaseRepository<Recipe>, IRepository<Recipe>
Если `BaseRepository<T>` будет реализоввывать `IRepository<T>`, то не надо будет дополнительно указывать `IRepository<Recipe>`

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/RecipeRepository.cs
> +            var recipe = Get(id);
Этот метод можно вынести в базовый класс

2020-09-03 14:40 UTC, alex-geraschenko commented on task2/Repositories/RecipeRepository.cs
> +            return (from r in Items
Этот метод можно вынести в базовый класс

2020-09-04 05:14 UTC, igor-tukalo commented on task2/Controls/CookingStepsControl.cs
> +            IdRecipe = idRecipe;
IdRecipe я использую в методах Controls, я конечно же могу передавать IdRecipe через параметры, но тогда придется таскать этот IdRecipe через все мои классы Navigation. Ведь у меня меню навигации два. Navigation для перехода между окнами в котором я могу вызывать только метод Add и отдельно ContextMenuNavigation в нем вызываются для конкретной выбраной записи медоты Edit, Delete. Так как ContextMenuNavigation можно вызывать только из Navigation и так как я обращаюсь через интерфейс к классам Controls я и решил передавать в конструктор Controls IdRecipe, иначе пришлось бы передавать IdRecipe в конструктор классов Navigation, а так у моих Navigation конструктор 
```
        readonly ICookingStepsControl CookingSteps;

        public CookingStepsNavigation(ICookingStepsControl cookingSteps)
        {
            CookingSteps = cookingSteps;
        }
```
где я всегда могу передать IdRecipe классам ContextMenuNavigation
`new ProgramMenu(new RecipesContextMenuNavigation(CookingSteps.IdRecipe, new RecipesControl(CookingSteps.UnitOfWork))).CallMenu();`

2020-09-04 05:26 UTC, igor-tukalo commented on task2/Repositories/AmountIngredientRepository.cs
> +            return (from a in Items
но у меня ведь обобщенные колекции public List<T> Items { get; set; }
```
            return (from a in Items
                    where a.Id == id
                    select a).FirstOrDefault();
```
и этот код не сработает. или имеется ввиду сделать их абстрактными или виртуальными?

2020-09-07 18:07 UTC, alex-geraschenko requested changes

2020-09-07 18:07 UTC, alex-geraschenko commented on task2/Interfaces/IBaseControl.cs
> +        public virtual void Add() { }
Все методы и свойста интерфейса публичны по-умолчанию. Объявлять `public` здесь не нужно

2020-09-07 18:07 UTC, alex-geraschenko commented on task2/Repositories/AmountIngredientRepository.cs
> +            return (from a in Items
> и этот код не сработает. или имеется ввиду сделать их абстрактными или виртуальными?

> но у меня ведь обобщенные колекции

Как раз поэтому код сработает

2020-09-07 18:07 UTC, alex-geraschenko commented on task2/Controls/CookingStepsControl.cs
> +            IdRecipe = idRecipe;
Звучит очень запутано, а значит хрупко. Я бы попробовал переосмыслить концепцию навигаторов

2020-09-09 07:47 UTC, alex-geraschenko requested changes

2020-09-09 07:47 UTC, alex-geraschenko commented on task2/Interfaces/IBaseControl.cs
> +        virtual void Add() { }
В интерфейсах не должно быть модификаторов

2020-09-09 07:47 UTC, alex-geraschenko commented on task2/Repositories/IRepository.cs
> +        abstract T Get(int id);
В интерфейсах не должно быть модификаторов

2020-09-09 07:47 UTC, alex-geraschenko commented on task2/Controls/BaseCategoriesRecipesControl.cs
> +        readonly protected CategoryRepository categoryRepository;
Принято сначала указывать `protected`, а потом `readonly`.

2020-09-09 07:47 UTC, alex-geraschenko commented on task2/Controls/BaseCategoriesRecipesControl.cs
> +        readonly protected CategoryRepository categoryRepository;
`protected` свойства принято называть в `PascalCase`

2020-09-09 07:47 UTC, alex-geraschenko commented on task2/Controls/BaseCategoriesRecipesControl.cs
> +    class BaseCategoriesRecipesControl : BaseControl
Базовые классы лучше делать абстрактными

2020-09-09 07:47 UTC, alex-geraschenko commented on task2/Controls/BaseCategoriesRecipesControl.cs
> +        public BaseCategoriesRecipesControl(IUnitOfWork unitOfWork) : base(unitOfWork)
Конструкторы в базовых классах лучше делать `protected`

2020-09-09 07:47 UTC, alex-geraschenko commented on task2/ViewNavigation/WindowNavigation/MainWindowNavigation.cs
> +                        new ProgramMenu(new RecipesNavigation(new CategoriesControl(new UnitOfWork()),new RecipesControl(new UnitOfWork()))).CallMenu();
Зачем дублировать создание `UnitOfWork`?

2020-09-09 08:37 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-09-09 08:40 UTC, merged