Задание 4
igor-tukalo/altexsoft-lab-2020-master pull request #7
Opened 2020-09-19 21:07 UTC by igor-tukalo

2020-09-23 14:38 UTC, serhii-shkodenko commented on HomeTask4.Cmd/Navigation/Navigation.cs
> +        public delegate void Method(int id);
Пожалуйста, поменяйте имя делегата на более описательное (descriptive). При именовании можно воспользоваться [этими гайдлайнами](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces#names-of-common-types).

2020-09-23 14:38 UTC, serhii-shkodenko commented on HomeTask4.Cmd/Navigation/Navigation.cs
> +        public void CallNavigation(List<EntityMenu> menuItems, Method selectedMethod)
Пожалуйста, поменяйте имя делегата на более описательное (descriptive). При именовании можно [воспользоваться этими гайдлайнами](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces#names-of-common-types).

2020-09-23 14:38 UTC, serhii-shkodenko commented on HomeTask4.Core/CRUD/SettingsControl.cs
> +namespace HomeTask4.Core.CRUD
Вижу, Вы испльзуете FxCop. Имя в неймспейсе CRUD будет [нарушением правила CA1709: Identifiers should be cased correctly](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1709?view=vs-2019). Сейчас анализатор не кидает ни ворнинга, ни ерора, однако это потому, что это правилао до сих пор не портировано для комплятора Roslyn.

2020-09-23 22:06 UTC, serhii-shkodenko commented on HomeTask4.Infrastructure/Data/EfRepository.cs
> +            await _context.SaveChangesAsync().ConfigureAwait(false);
В ASP.NET Core await не захватывает контекст, поэтому в данном случае вызывать ConfigureAwait(false) нет смысла. Пожалуйста, пройдитесь по всему заданию и поправьте.

2020-09-23 22:06 UTC, serhii-shkodenko commented on HomeTask4.Infrastructure/Data/EfRepository.cs
> +            return await Task.Run(() => _context.Set<T>().AsNoTracking().Where(predicate).ToList()).ConfigureAwait(false);
Я не вижу причин создавать асинхронную обертку над этим синхронным кодом. Больше можно [прочитать здесь](https://devblogs.microsoft.com/pfxteam/should-i-expose-asynchronous-wrappers-for-synchronous-methods/). Пройдитесь по коду и поправьте в других местах.

2020-09-23 22:06 UTC, serhii-shkodenko commented on HomeTask4.Infrastructure/Data/EfRepository.cs
> +            return await Task.Run(() => _context.Set<T>().AsNoTracking().Where(predicate).ToList()).ConfigureAwait(false);
Если Вы хотите создать асинхронный метод, возможно Вам подойдет `ToListAsync()`.

2020-09-23 22:06 UTC, serhii-shkodenko commented on HomeTask4.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddScoped<IUnitOfWork, UnitOfWork>();
Здесь должны быть все Ваши репозитории и контроллеры.

2020-09-23 22:23 UTC, serhii-shkodenko commented on HomeTask4.Core/Controllers/CategoriesController.cs
> +    public class CategoriesController : BaseController, ICategoriesControl
Пожалуйста, поправьте имена для Ваших интерфейсов в соответствии с [гайдлайнами](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces). Пройдитесь по всему коду. 

✔️ DO ensure that the names differ only by the "I" prefix on the interface name when you are defining a class–interface pair where the class is a standard implementation of the interface.

2020-09-23 22:32 UTC, serhii-shkodenko commented on HomeTask4.Cmd/Navigation/BaseNavigation.cs
> +            UnitOfWork = HostBuild.Services.GetRequiredService<IUnitOfWork>();
Подумайте, как здесь можно использовать Dependency Injection и IoC контейнер.

2020-09-23 22:34 UTC, serhii-shkodenko commented on HomeTask4.Cmd/Navigation/BaseNavigation.cs
> +        protected static IHostBuilder CreateHostBuilder(bool isConsole)
В этом месте этого метода быть не должно. Используйте Dependency Injection и IoC контейнер.

2020-09-25 07:35 UTC, igor-tukalo commented on HomeTask4.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddScoped<IUnitOfWork, UnitOfWork>();
Но у меня один Generic репозиторий, а к своим контроллерам я обращаюсь через UnityOfWork. Как я понял HostBuilder нужен для внедрения зависимостей, настройки конфигурации приложения, ведения лога и другое. И вызывать его можно его только один раз для инициализации. Инициализируется хост методом Build () и перед его вызовом можно настроить доп параметры в ConfigureServices(), а класс ServiceCollectionExtensions.cs содержит метод AddInfrastructure где указывается строка подключения к БД и внедрения зависимостей. Я не совсем понимаю как правильно использовать внедрение зависимостей если я добавлю контроллеры в services.AddScoped

2020-09-28 13:41 UTC, alex-geraschenko requested changes
У Вас слишком переусложнена логика работы с меню. В ней нарушен принцип **Dependency Inversion**

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/App.config
> +<configuration>
Вместо этого файла воспользуйтесь `appsettings.json`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/BaseNavigation.cs
> +            new Navigation().CallNavigation(ItemsMenu, SelectMethodMenu);
Нарушение принципа **Dependency Inversion**

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/CategoriesContextMenuNavigation.cs
> +        private readonly int Idcategory;
Приватные поля принято называть в `camelCase`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/CategoriesContextMenuNavigation.cs
> +        private readonly int Idcategory;
С точки зрения английского языка правильное название должно быть `categoryId`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/CategoriesContextMenuNavigation.cs
> +        private readonly ICategoriesController Categories;
Приватные поля принято называть в `camelCase`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/CategoriesContextMenuNavigation.cs
> +        private readonly ICategoriesController Categories;
Имя поля не соответствует содержимому. Должно быть `categoriesController`, а еще лучше использовать `_` вначале: `_categoriesController`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/CategoriesContextMenuNavigation.cs
> +        public CategoriesContextMenuNavigation(IUnitOfWork unitOfWork, int idCategory, ICategoriesController categories) : base(unitOfWork)
Имя параметра `categories` не соответствует содержимому. Должно быть `categoriesController`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/CookingStepsContextMenuNavigation.cs
> +        public CookingStepsContextMenuNavigation(IUnitOfWork unitOfWork, int idCookingStep, int idRecipe, ICookingStepsController cookingSteps) : base(unitOfWork)
Имя параметра `cookingSteps` не соответствует содержимому. Должно быть `cookingStepsController`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/CookingStepsContextMenuNavigation.cs
> +        private readonly ICookingStepsController CookingSteps;
Приватные поля принято называть в `camelCase`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/CookingStepsContextMenuNavigation.cs
> +        private readonly ICookingStepsController CookingSteps;
Имя поля не соответствует содержимому. Должно быть `cookingStepsController`, а еще лучше использовать _ вначале: `_cookingStepsController`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/CookingStepsContextMenuNavigation.cs
> +        private readonly int IdCookingStep;
С точки зрения английского языка правильное название должно быть `cookingStepId`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/CookingStepsContextMenuNavigation.cs
> +        private readonly int IdRecipe;
С точки зрения английского языка правильное название должно быть `recipeId`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/IngredientsContextMenuNavigation.cs
> +        private readonly int IdIngredient;
С точки зрения английского языка правильное название должно быть `ingredientId`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/IngredientsContextMenuNavigation.cs
> +        private readonly IIngredientsController Ingredients;
Приватные поля принято называть в `camelCase`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/ContextMenuNavigation/IngredientsContextMenuNavigation.cs
> +        private readonly IIngredientsController Ingredients;
Имя поля не соответствует содержимому. Должно быть `ingredientsController`, а еще лучше использовать _ вначале: `_ingredientsController`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/BaseNavigation.cs
> +        internal IUnitOfWork UnitOfWork { get; set; }
Вместо `UnitOfWork` в навигации лучше использовать контроллеры

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/BaseNavigation.cs
> +        internal IUnitOfWork UnitOfWork { get; set; }
Вместо `internal` лучше использовать `protected`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.SharedKernel/Validation.cs
> +        public int ValidNumber(string number)
Имя метода должно быть глаголом!

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.SharedKernel/Validation.cs
> +        public double ValidDouble(string number)
Имя метода должно быть глаголом!

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.SharedKernel/Validation.cs
> +        public string NullOrEmptyText(string text)
Имя метода должно быть глаголом!

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.SharedKernel/Validation.cs
> +            while (batchNum < 1 || batchNum > countBatch);
Дублирование условия. Пересмотрите логику

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.SharedKernel/Validation.cs
> +            else
`else` избыточно

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.SharedKernel/Validation.cs
> +        public ConsoleKey YesNo()
Имя метода должно быть глаголом!

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.SharedKernel/Validation.cs
> +                if (!string.IsNullOrWhiteSpace(number) && isNum)
Избыточная проверка на пустую строку

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.SharedKernel/Validation.cs
> +        public double ValidDouble(string number)
Методы `ValidNumber` и `ValidDouble` дублируют логику, за исключением одной строки. Постарайтесь оптимизировать

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.SharedKernel/HomeTask4.SharedKernel.csproj
> +    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
Зачем вам столько зависимостей?

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/HomeTask4.Infrastructure.csproj
> +    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.8" />
Зачем Вам столько зависимостей?

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddScoped<IUnitOfWork, UnitOfWork>();
Обращаться к контроллерам через UnitOfWork плохая идея. Не UnitOfWork должен знать о контроллерах, а контроллеры должны использовать UnitOfWork.
Вы можете создать отдельный метода расширения для контроллеров и вызвать его рядом с `AddInfrastructure`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/Config/TempEntityConfig.cs
> +    public class TempEntityConfig : IEntityTypeConfiguration<TempEntity>
Этот класс был добавлен только для примера конфигурации сущностей Вашего приложения

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/AppDbContext.cs
> +                modelBuilder.ApplyConfiguration(new TempEntityConfig());
А где конфигурации для сущностей Вашего приложения?

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/HomeTask4.Core.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.8" />
Зачем Вам столько зависимостей?

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Entities/TempEntity.cs
> +    public class TempEntity : BaseEntity
Этот класс был добвлен только как пример для сущнощностей Вашего приложения

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Entities/EntityMenu.cs
> +    public class EntityMenu : BaseEntity
Не стоит смешивать доменные сущности (категории, рецепты и т.д.) и вспомагательные для работы меню

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Entities/CategoryNode.cs
> +    public class CategoryNode : BaseEntity
Зачем Вам этот класс?

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/SettingsController.cs
> +        public void EditBatch()
Зачем реализовывать то, что может никогда не пригодиться (и не было в задании)? Ведь можно за пару секунд руками исправить параметр в файле и не создавать отдельный код для управления этим параметром.
Здесть Вы нарушили принцип `YAGNI`.

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/RecipesController.cs
> +        private List<AmountIngredient> AmountIngredients => UnitOfWork.Repository.GetList<AmountIngredient>();
Не стоит сразу все вычитывать из базы, а потом в памяти фильтровать. Лучше делать фильтрацию на уровне базы

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/RecipesController.cs
> +            foreach (AmountIngredient a in AmountIngredients.Where(x => x.RecipeId == recipe.Id))
Однобуквенные переменные - признак плохого кода

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/RecipesController.cs
> +            foreach (CookingStep s in CookingSteps.Where(x => x.RecipeId == recipe.Id).OrderBy(x => x.Step))
Однобуквенные переменные - признак плохого кода

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/RecipesController.cs
> +                    items.Add(new EntityMenu() { Id = recipe.Id, Name = $"  {recipe.Name}", ParentId = recipe.CategoryId, TypeEntity = "recipe" });
Контроллер ничего не должен знать о меню

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/RecipesController.cs
> +        private string IsNameMustNotExist(string name)
С точки зрения английского языка имя этого метода бессмысленно. Постарайтесь переименовать его так, чтобы было понятно, что он делает

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/RecipesController.cs
> +            while (Recipes.Exists(x => x.Name.ToLower(CultureInfo.CurrentUICulture) == name.ToLower(CultureInfo.CurrentUICulture)))
Лучше проверять наличие существования имени в базе, а не в уже вычитанной коллекции. При этом не надо будет делать преобразование с `CultureInfo`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/IngredientsControl.cs
> +        private string IsNameMustNotExist(string name)
С точки зрения английского языка имя этого метода бессмысленно. Постарайтесь переименовать его так, чтобы было понятно, что он делает

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/RecipeIngredientsController.cs
> +        private List<AmountIngredient> AmountIngredients => UnitOfWork.Repository.GetList<AmountIngredient>();
Не стоит сразу все вычитывать из базы, а потом в памяти фильтровать. Лучше делать фильтрацию на уровне базы

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/RecipeIngredientsController.cs
> +                foreach (AmountIngredient a in AmountIngredients.Where(x => x.RecipeId == idRecipe))
Однобуквенные переменные - признак плохого кода

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/RecipeIngredientsController.cs
> +                            itemsMenu.Add(new EntityMenu() { Id = a.Id, Name = $"    {i.Name} - {a.Amount} {a.Unit}", ParentId = a.RecipeId, TypeEntity = "ingrRecipe" });
Контроллер ничего не должен знать о меню

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/IngredientsControl.cs
> +                            itemsMenu.Add(new EntityMenu() { Id = batch.Id, Name = $"    {batch.Name}", TypeEntity = "ingr" });
Контроллер ничего не должен знать о меню

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/IngredientsControl.cs
> +        private List<Ingredient> Ingredients => UnitOfWork.Repository.GetList<Ingredient>();
Не стоит сразу все вычитывать из базы, а потом в памяти фильтровать. Лучше делать фильтрацию на уровне базы

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/CookingStepsController.cs
> +        private List<CookingStep> CookingSteps => UnitOfWork.Repository.GetList<CookingStep>();
Не стоит сразу все вычитывать из базы, а потом в памяти фильтровать. Лучше делать фильтрацию на уровне базы

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/CookingStepsController.cs
> +                        itemsMenu.Add(new EntityMenu() { Id = s.Id, Name = $"    {s.Step}. {s.Name}", ParentId = s.RecipeId });
Контроллер ничего не должен знать о меню

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/CookingStepsController.cs
> +                foreach (CookingStep s in CookingSteps.Where(x => x.RecipeId == idRecipe))
Однобуквенные переменные - признак плохого кода

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/CategoriesController.cs
> +        private List<Category> Categories => UnitOfWork.Repository.GetList<Category>();
Не стоит сразу все вычитывать из базы, а потом в памяти фильтровать. Лучше делать фильтрацию на уровне базы

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/BaseController.cs
> +            ValidManager = new Validation();
Нарушение принципа **Dependency Inversion**

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/BaseCategoriesRecipesControl.cs
> +        internal readonly CategoryRepository CategoryRepository;
Вместо `internal` лучше использовать `protected`

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Program.cs
> +        /// < returns >< see cref="IHostBuilder" /> hostBuilder</returns>
Уберите лишние пробелы в тегах

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Cmd/Program.cs
> +            ProgramMenu programMenu = new ProgramMenu(nav);
Нарушение принципа **Dependency Inversion**

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/CategoriesController.cs
> +        private string IsNameMustNotExist(string name)
С точки зрения английского языка имя этого метода бессмысленно. Постарайтесь переименовать его так, чтобы было понятно, что он делает

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/CategoriesController.cs
> +        private string IsNameMustExist(string name)
С точки зрения английского языка имя этого метода бессмысленно. Постарайтесь переименовать его так, чтобы было понятно, что он делает

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/CategoriesController.cs
> +            } while (!Categories.Exists(x => x.Name == name));
Дублирование условия, пересмотрить логику метода

2020-09-28 13:41 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/CategoriesController.cs
> +                items.Add(new EntityMenu() { Id = thisEntity.Id, Name = $"{new string('-', level)}{thisEntity.Name}", ParentId = thisEntity.ParentId });
Контроллер ничего не должен знать о меню

2020-09-29 06:30 UTC, igor-tukalo commented on HomeTask4.Core/Controllers/SettingsController.cs
> +        public void EditBatch()
Batch я использую для разбиения списка на страницы. К примеру у меня 100 ингредиентов и я их делю по 20 на страницу.

2020-09-29 14:51 UTC, igor-tukalo commented on HomeTask4.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddScoped<IUnitOfWork, UnitOfWork>();
Ок как HomeTask4.Core переделать я кажется понял, но не совсем понятно как должен выглядеть HomeTask4.Cmd я должен сделать мои классы Navigations как сервисы и потом как то получать эти сервисы через интерфейсы чтобы не нарушать Dependency Inversion?

2020-09-29 15:25 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/SettingsController.cs
> +        public void EditBatch()
Еще раз перечитайте мой коментарий. Я говорю не про испольование `Batch`, а про код для его редактирования

2020-10-07 10:55 UTC, serhii-shkodenko requested changes

2020-10-07 10:55 UTC, serhii-shkodenko commented on HomeTask4.Core/HomeTask4.Core.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
Обновите проект до .NET Core 3.1. Все остальные тоже просмотрите и поправьте, если нужно.

2020-10-07 10:55 UTC, serhii-shkodenko commented on HomeTask4.Infrastructure/Data/EfRepository.cs
> +            return await GetAllItems<T>().SingleOrDefaultAsync(predicate);
Конструкцию `return await` сократите до `return`. Соответственно `async` тогда тоже не будет нужен. Здесь необязетельно разворачивать машину состояний. Наверх вернется `Task`, выполненеие которой Вы можете асинхронно подождать с помощью `await`. Таким образом, вместо разворачиваний двух машин состояний, развернется только одна. Поправьте во всех остальных случаях.

2020-10-07 10:57 UTC, serhii-shkodenko commented on HomeTask4.Core/HomeTask4.Core.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
Да, попутало меня. Конечно же, до netstandard2.1 обновите, пожалуйста )

2020-10-21 09:58 UTC, alex-geraschenko requested changes
В 4 задании не должно быть кода из 5 задания. Для этого и существуют разные ветки в гите
В 4 задании не должно быть кода из 6 задания. Для этого и существуют разные ветки в гите

2020-10-21 09:58 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/BaseController.cs
> +        protected IOptions<CustomSettings> CustomSettingsApp { get; }
Это свойство используется только в одном контроллере, поэтому нет смысла держать его в базовом

2020-10-21 09:58 UTC, alex-geraschenko commented on HomeTask4.Cmd/ValidationNavigation.cs
> +    public class ValidationNavigation : IValidationNavigation
Название класса не соответствует его функционалу. Как минимум методы `ShowYesNoAsync` и `WrapTextAsync` не имеют отношения к валидации

2020-10-21 09:58 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/EfRepository.cs
> +        public IQueryable<T> GetAllItems<T>() where T : BaseEntity
Выставление наружу `IQueryable` интерфейса считается плохой практикой, т.к. происходит так называемая "протечка" слоев. Это когда верхний слой (бизнес логика) знает о деталях реализации нижнего слоя.

2020-10-21 09:58 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/UnitOfWork.cs
> +        public IOptions<CustomSettings> Settings { get; }
Для чего нужно свойсто `Settings` внутри `UnitOfWork`?

2020-10-21 09:58 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Extensions/HostBuilderExtensions.cs
> +    public static class HostBuilderExtensions
Я Вас просил упростить код, а Вы добавили еще больше сложностей

2020-10-22 10:18 UTC, closed without merging