Tasks/task4
igor-tukalo/altexsoft-lab-2020-master pull request #9
Opened 2020-10-22 12:01 UTC by igor-tukalo

2020-10-27 19:17 UTC, alex-geraschenko requested changes

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/EfRepository.cs
> +                throw new Exception(ex.Message);
Не стоит переопределять исключения, за исключением кастомных доменных исключений. Т.к. теряется внутренняя информация об исключении

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/EfRepository.cs
> +                throw new Exception(ex.Message);
Не стоит переопределять исключения, за исключением кастомных доменных исключений. Т.к. теряется внутренняя информация об исключении

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/EfRepository.cs
> +                throw new Exception(ex.Message);
Не стоит переопределять исключения, за исключением кастомных доменных исключений. Т.к. теряется внутренняя информация об исключении

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/Config/RecipeConfig.cs
> +            }
Не хватает конфигурации навигационных свойств

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/Config/IngredientConfig.cs
> +            }
Не хватает конфигурации навигационных свойств

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/Config/CookingStepConfig.cs
> +                builder.Property(p => p.RecipeId).IsRequired();
Не хватает конфигурации навигационных свойств

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/Config/CategoryConfig.cs
> +                builder.HasIndex(u => u.Name).IsUnique();
Не хватает конфигурации навигационных свойств

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/Config/AmountIngredientConfig.cs
> +                builder.Property(p => p.IngredientId).IsRequired();
Не хватает конфигурации навигационных свойств

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Core/Interfaces/Navigation/IValidationNavigation.cs
> +    public interface IConsoleHelper
Имя файла не соответствует имени интерфейса

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Core/Interfaces/Navigation/IValidationNavigation.cs
> +        Task<ConsoleKey> ShowYesNoAsync();
В `Core` не должно быть зависимости от консоли: `ConsoleKey`

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/BaseCategoriesRecipesControl.cs
> +        internal readonly CategoryRepository CategoryRepository;
Эти поля лучше сделать `protected` свойствами

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/NavigationManager.cs
> +        private Task ClearAreaAsync(int top, int left, int height, int width)
Зачем делать этот метод асинхронным?

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/NavigationManager.cs
> +        private async Task<int> PrintMenuAsync()
Зачем делать этот метод асинхронным?

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Cmd/Navigation/BaseNavigation.cs
> +        protected IConsoleHelper ValidationNavigation { get; }
Название свойства противоречит его типу

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Infrastructure/Data/UnitOfWork.cs
> +        public IOptions<CustomSettings> Settings { get; }
Где используется это свойство?

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/CategoriesController.cs
> +                throw new Exception(ex.Message);
Не надо переопределять исключение таким же исключением. В этом случае теряется важная информация о деталях исключения. В данном случае вообще нет смысла перехватывать исключения

2020-10-27 19:17 UTC, alex-geraschenko commented on HomeTask4.Core/Controllers/CookingStepsController.cs
> +            await UnitOfWork.SaveChanges();
Т.к. у Вас в `DeleteAsync` вызывается `SaveChanges`, то дополнительно вызывать его нет смысла

2020-10-29 06:54 UTC, igor-tukalo commented on HomeTask4.Core/Interfaces/Navigation/IValidationNavigation.cs
> +        Task<ConsoleKey> ShowYesNoAsync();
Может лучше вынести все интерфейсы с Navigation в cmd? Они ведь только там будут использоваться.

2020-10-30 19:32 UTC, alex-geraschenko approved these changes
Выглядит хорошо, можно мержить

2020-11-01 16:36 UTC, merged